Add updating status of BecauseOfs when running scenarios
dolittle-runtime/IntegrationTests pull request #2
Opened 2020-05-27 22:34 UTC by jakhog

It's not really pretty, but it works :)

The `OverwritingConsoleRenderer` should probably get a new name, and be placed somewhere else where it could potentially be re-used elsewhere.

The `RunStatus` could also use some love, and potentially could be used on other components as well that we would like to monitor the status of.

We could also print the running time of each BecauseOf, but that requires a bit more clearing of the console. Right now each line has the exact same length every time it is printed, which makes things easy.

2020-06-03 07:27 UTC, einari requested changes
Looks fine and looking forward to see spinners and progress :) 
I was just curious to why you'd expand the expressions for the subscription setup. I couldn't see anything in the code that required it.

2020-06-03 07:27 UTC, einari commented on Source/TheAviator/flights/FlightReporter.ts
> +        flight.scenario.subscribe(scenario => this.outputScenario(scenario));
Why expand these?

2020-06-03 07:38 UTC, einari requested changes
Second look through and I saw multiple classes in the reporter file. 
Separate these into their own files.

2020-06-03 07:38 UTC, einari commented on Source/TheAviator/flights/FlightReporter.ts
> +class NewlineCountingStream extends Transform {
Separate into its own file

2020-06-03 07:38 UTC, einari commented on Source/TheAviator/flights/FlightReporter.ts
> +class NewlineCounter {
Same as above - own file

2020-06-03 07:38 UTC, einari commented on Source/TheAviator/flights/FlightReporter.ts
> +class OverwritingConsoleRenderer {
Same as above - own file.
You can include the delegate type in the same as well.

2020-06-03 07:39 UTC, einari commented
For the `OverwritingConsoleRenderer`- could a better name be `InPlaceConsoleRenderer`. If I understand it correctly its basically overwriting at a specific location, in place kinda..  ??

2020-06-15 20:38 UTC, woksin commented
Should we register issues for the comments @einari has or are you on top of this @jakhog? Would be cool tho have this 😄

2023-05-30 05:44 UTC, closed without merging